# python plot_entropy.py with exp=CVPR_sampler_resnet18_cifar10
# python plot_entropy.py with exp=CVPR_corr_labels_resnet18_cifar10
# python plot_entropy.py with exp=CVPR_corr_labels_resnet34_cifar10
# python plot_entropy.py with exp=CVPR_label_corr_resnet18_cifar10
# python plot_entropy.py with exp=CVPR_MD_invtunnel_resnet18_cifar10
# python plot_entropy.py with exp=CVPR_MD_resnet18_cifar10
# python plot_entropy.py with exp=CVPR_sampler_resnet34_cifar10
python plot_entropy.py with exp=CVPR_sampler_resnet18_cinic
python plot_entropy.py with exp=CVPR_sampler_resnet18_cifar100
python plot_entropy.py with exp=CVPR_sampler_resnet18_cifar10
python plot_entropy.py with exp=CVPR_annealing_resnet18_cifar10
python plot_entropy.py with exp=CVPR_corr_labels_resnet18_cifar100
python plot_entropy.py with exp=CVPR_default_resnet18_cifar10
python plot_entropy.py with exp=CVPR_default_resnet18_cifar100
python plot_entropy.py with exp=CVPR_MD_invtunnel_resnet18_cifar10
python plot_entropy.py with exp=CVPR_MD_resnet18_cifar10
python plot_entropy.py with exp=CVPR_MD_resnet18_cifar100
python plot_entropy.py with exp=CVPR_sampler_resnet10_cifar100
python plot_entropy.py with exp=CVPR_test_sampler_resnet18_cifar10