python plot_entropy.py with exp=CVPR_sampler_resnet18_cifar10
python plot_entropy.py with exp=CVPR_corr_labels_resnet18_cifar10
python plot_entropy.py with exp=CVPR_corr_labels_resnet34_cifar10
python plot_entropy.py with exp=CVPR_label_corr_resnet18_cifar10
python plot_entropy.py with exp=CVPR_MD_invtunnel_resnet18_cifar10
python plot_entropy.py with exp=CVPR_MD_resnet18_cifar10
python plot_entropy.py with exp=CVPR_sampler_resnet18_cifar10
python plot_entropy.py with exp=CVPR_sampler_resnet34_cifar10