# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode=2 dataset.perc=0.1
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode=2 dataset.perc=0.2
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode=2 dataset.perc=0.3
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode=2 dataset.perc=0.4
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode=2 dataset.perc=0.5
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode=2 dataset.perc=0.6
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode=2 dataset.perc=0.7
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode=2 dataset.perc=0.8
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode=2 dataset.perc=0.9
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' dataset.pilot_samp=invtunnel save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.1
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' dataset.pilot_samp=invtunnel save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.2
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' dataset.pilot_samp=invtunnel save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.3
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' dataset.pilot_samp=invtunnel save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.4
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' dataset.pilot_samp=invtunnel save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.5
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' dataset.pilot_samp=invtunnel save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.6
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' dataset.pilot_samp=invtunnel save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.7
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' dataset.pilot_samp=invtunnel save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.8
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' dataset.pilot_samp=invtunnel save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.9
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.1
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.2
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.3
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.4
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.5
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.6
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.7
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.8
# python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='CVPR_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet10' save=True dataset.mode_source=counter dataset.mode=1 dataset.perc=0.9
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=f_events dataset.mode=6 dataset.perc=0.1
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=f_events dataset.mode=6 dataset.perc=0.2
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=f_events dataset.mode=6 dataset.perc=0.3
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=f_events dataset.mode=6 dataset.perc=0.4
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=f_events dataset.mode=6 dataset.perc=0.5
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=f_events dataset.mode=6 dataset.perc=0.6
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=f_events dataset.mode=6 dataset.perc=0.7
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=f_events dataset.mode=6 dataset.perc=0.8
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=f_events dataset.mode=6 dataset.perc=0.9
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=cum_loss dataset.mode=6 dataset.perc=0.1
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=cum_loss dataset.mode=6 dataset.perc=0.2
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=cum_loss dataset.mode=6 dataset.perc=0.3
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=cum_loss dataset.mode=6 dataset.perc=0.4
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=cum_loss dataset.mode=6 dataset.perc=0.5
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=cum_loss dataset.mode=6 dataset.perc=0.6
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=cum_loss dataset.mode=6 dataset.perc=0.7
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=cum_loss dataset.mode=6 dataset.perc=0.8
python main_CVPR.py with j=30 b=256 dataset.name='cinic' exp='ECCV_MD' sampler='default' wd=5e-4 arch='resnet18' dataset.pilot_arch='resnet18' save=True dataset.mode_source=cum_loss dataset.mode=6 dataset.perc=0.9
