python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=tunnel b=256 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.3 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=tunnel b=256 temperature=1 arch=resnet18 normalizer=True corr_labels=0.1 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=tunnel b=256 temperature=1 arch=resnet18 normalizer=True corr_labels=0.2 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=tunnel b=256 temperature=1 arch=resnet18 normalizer=True corr_labels=0.3 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=tunnel b=512 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.1 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=tunnel b=512 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.2 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=tunnel b=512 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.3 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=tunnel b=512 temperature=1 arch=resnet18 normalizer=True corr_labels=0.1 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=tunnel b=512 temperature=1 arch=resnet18 normalizer=True corr_labels=0.2 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=tunnel b=512 temperature=1 arch=resnet18 normalizer=True corr_labels=0.3 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=128 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.1 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=128 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.2 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=128 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.3 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=128 temperature=1 arch=resnet18 normalizer=True corr_labels=0.1 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=128 temperature=1 arch=resnet18 normalizer=True corr_labels=0.2 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=128 temperature=1 arch=resnet18 normalizer=True corr_labels=0.3 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=256 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.1 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=256 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.2 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=256 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.3 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=256 temperature=1 arch=resnet18 normalizer=True corr_labels=0.1 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=256 temperature=1 arch=resnet18 normalizer=True corr_labels=0.2 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=256 temperature=1 arch=resnet18 normalizer=True corr_labels=0.3 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=512 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.1 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=512 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.2 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=512 temperature=0.1 arch=resnet18 normalizer=True corr_labels=0.3 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=512 temperature=1 arch=resnet18 normalizer=True corr_labels=0.1 g=1
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=512 temperature=1 arch=resnet18 normalizer=True corr_labels=0.2 g=0
python main_CVPR.py with save=True j=10 dataset.name='cifar10' exp='CVPR_label_corr' tfl=True sampler=invtunnel b=512 temperature=1 arch=resnet18 normalizer=True corr_labels=0.3 g=1