python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.1 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.2 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.3 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.4 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.5 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.6 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.7 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.8 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.9 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.1 dataset.mode=1 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.2 dataset.mode=1 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.3 dataset.mode=1 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.4 dataset.mode=1 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.5 dataset.mode=1 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.6 dataset.mode=1 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.7 dataset.mode=1 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.8 dataset.mode=1 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.9 dataset.mode=1 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.1 dataset.mode=2 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.2 dataset.mode=2 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.3 dataset.mode=2 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.4 dataset.mode=2 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.5 dataset.mode=2 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.6 dataset.mode=2 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.7 dataset.mode=2 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.8 dataset.mode=2 dataset.pilot_arch='resnet10'
python main_lt.py with dataset.name='cifar100' save=True wd=5e-4 arch='resnet18' dataset.perc=0.9 dataset.mode=2 dataset.pilot_arch='resnet10'
#python main_lt.py with dataset.name='cifar100' epochs=20 wd=1e-3 arch='resnet10' pilot=True save=True